name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - dill
  - pandas
  - bokeh
  - dask
  - zarr
  - rioxarray
  - hvplot
  - ipyleaflet
  - cartopy 
  - pyam
  - pathlib
  - dask-geopandas
  - xarray
  - holoviews
  - pystac-client
  - python-dotenv
  - pip
  - rasterio
  - spatialpandas
  - pystac
  - typing
  - fsspec
  - shapely
  - geoviews
  - geopandas
  - colorcet
  - pip:
      - stac-geoparquet 
      - coclico