name: coclico_binder

channels:
    - conda-forge

dependencies:
    - aiohttp
    #- black
    #- bokeh
    - cartopy
    - cdsapi
    #- cfchecker
    #- colormaps
    - contextily
    - dask
    - distributed
    #- folium
    #- fsspec
    - gdal
    #- geojson
    - geopandas
    - ipykernel
    #- ipyleaflet
    #- ipympl
    #- jupyter
    #- jupyter_bokeh
    - jupyterlab-myst
    - jupyterlab
    - matplotlib
    - netcdf4
    - notebook
    - numpy
    #- odc-stac
    #- opencv
    - openpyxl
    - osmnx
    #- pathlib
    - pandas
    - pip
    - planetary-computer
    - pooch
    #- pyarrow
    - pyogrio
    - pyproj
    - pystac-client
    - python
    #- python-dotenv
    - rasterio
    - rasterstats
    - requests
    - rioxarray
    #- scikit-learn
    #- scipy
    #- setuptools
    - shapely
    - xarray
    - zarr
    - pip:
        - damagescanner
        #- duckdb
        #- stac-geoparquet
        #- xstac
