name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - dill
  - pandas
  - bokeh
  - dask
  - zarr
  - rioxarray
  - hvplot
  - ipyleaflet
  - cartopy 
  - pyam
  - pathlib
  - dask-geopandas
  - xarray
  - holoviews
  # - pystac_client
  # - copy
  # - python-dotenv
  # - rasterio
  # - spatialpandas
  # - os
  # - pystac
  # - typing
  # - fsspec
  # - shapely
  # - sys
  # - geoviews
  # - geopandas
  # - colorcet
  # - uuid
  # - warnings
  # - pip:
  #     - stac_geoparquet 
      #- coclico