name: coclico_binder

channels:
    - conda-forge

dependencies:
    - aiohttp=3.9.5
    - cartopy=0.23.0
    - cdsapi=0.7.0
    - contextily=1.6.0
    - dask=2024.7.0
    - distributed=2024.7.0
    - gdal=3.9.1
    - geopandas=1.0.1
    - ipykernel=6.29.5
    - jupyterlab-myst=2.4.2
    - jupyterlab=4.2.3
    - matplotlib=3.8.4
    - netcdf4=1.7.1
    - notebook=7.2.1
    - numpy=1.26.4
    - openpyxl=3.1.4
    - osmnx=1.9.3
    - pandas=2.2.2
    - pip
    - planetary-computer=1.0.0
    - pooch=1.8.2
    - pyogrio=0.8.0
    - pyproj=3.6.1
    - pystac-client=0.8.2
    - python=3.11
    - rasterio=1.3.10
    - rasterstats=0.19.0
    - requests=2.32.3
    - rioxarray=0.15.7
    - shapely=2.0.4
    - xarray=2024.6.0
    - zarr=2.18.2
    - pip:
        - damagescanner==0.7
