channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - ipykernel
  - nb_conda
  - jupyterlab
  - dask-labextension
  - jupyterlab_code_formatter
  - jupyterlab_vim # jupyterlab-contrib/jupyterlab-vim
  - jupyterlab-git
  - ipywidgets
  - geopandas
  - pygeos
  - pyogrio
  - dask
  - distributed
  - dask-geopandas
  - nodejs
  - xarray
  - netcdf4
  - numpy
  - pandas
  - matplotlib
  - folium
  - mapclassify
  - colormaps
  - pyam
  - cartopy
  - contextily
  - pyarrow
  - rasterio
  - rioxarray
  - scipy
  - bandit
  - isort
  - black
  - zarr
  - h5py
  - fiona
  - geojson
  - pystac
  - pystac-client
  - python-dotenv
  - adlfs
  - gcsfs
  - tqdm
  - hvplot
  - datashader
  - geoviews
  - spatialpandas
